version: '2'
services:
  mysql:
    tty: true
    image: mysql:5.7
    ports:
      - "13306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  ruby:
    tty: true
    image: ruby:2.2
    container_name: ruby
    links:
      - mysql
